### PR TITLE
prevent a panic on windows 7 when host can not be found

### PR DESCRIPTION
**Pull request by vjeantet**

### CODE REVIEW

**Comment by zstyblik** [comment]
@vjeantet, please, can you elaborate on this PR? Because it doesn't make sense to me. In the broader context:

```
            // if len(hosts) == 0 is already checked here
            if err != nil || len(hosts) == 0 {
                return hostname
            }
            if len(hosts) == 0 {
                return "unknow"
            }
```

Thanks.

**Comment by vjeantet** [comment]
Ok i will do it with an exemple to reproduce error

**Comment by zstyblik** [comment]
Closing due to inactivity. Feel free to re-open/open new PR.

Thanks.

**Comment by vjeantet** [comment]
Hello, sorry about my PR, my repo was not updated, my problem was fixed in previous commit, related to #1

**Comment by zstyblik** [comment]
No problem. Glad to hear that issue is fixed :)

**Pull request closed without merging**
